services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: exness-timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Rakesh
      POSTGRES_PASSWORD: rakeshsdlccorp
      POSTGRES_DB: cfd_db
    volumes:
      - timescale_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: exness-redis
    ports:
      - "6380:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: exness-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: exness-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: exness-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://exness-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test:
        ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: exness-backend
    depends_on:
      - timescaledb
      - redis
      - kafka
    ports:
      - "4000:4000"
    env_file:
      - .env
  price-poller:
    build:
      context: .
      dockerfile: apps/price-poller/Dockerfile
    container_name: exness-price-poller
    depends_on:
      - redis
      - kafka
    env_file:
      - .env
  websocket:
    build:
      context: .
      dockerfile: apps/websocket/Dockerfile
    container_name: exness-websocket
    depends_on:
      - redis
      - kafka
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  timescale_data:
